language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
# Laravel 6.x
  - php: 7.2
    env: LARAVEL=^6.0 TESTBENCH=^4.0 PHPUNIT=~8.0
  - php: 7.3
    env: LARAVEL=^6.0 TESTBENCH=^4.0 PHPUNIT=~8.0
  - php: 7.4
    env: LARAVEL=^6.0 TESTBENCH=^4.0 PHPUNIT=~8.0

# Laravel 7.x
  - php: 7.2
    env: LARAVEL=^7.0 TESTBENCH=^5.0 PHPUNIT=~9.0
  - php: 7.3
    env: LARAVEL=^7.0 TESTBENCH=^5.0 PHPUNIT=~9.0
  - php: 7.4
    env: LARAVEL=^7.0 TESTBENCH=^5.0 PHPUNIT=~9.0

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update --stable --no-interaction
  - composer require orchestra/testbench:$TESTBENCH orchestra/database:$ORCHESTRA_DATABASE phpunit/phpunit:$PHPUNIT --no-update --no-interaction --dev

install:
  - travis_retry composer install --no-suggest --no-interaction

script:
  - vendor/bin/phpunit --verbose --configuration phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
