language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
# Laravel 7.x
  - php: 7.2
  - php: 7.3
  - php: 7.4

+before_install:
  - sudo apt-get update
  - sudo apt-get -y install graphviz

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update --stable --no-interaction

install:
  - travis_retry composer install --no-suggest --no-interaction

script:
  - vendor/bin/phpunit --verbose --configuration phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
